version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "go"
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: weekly